version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "913862848426"
    AWS_REGION: "eu-west-1"
    ECR_REPO_NAME: "tipstaff-ecr-repo"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - where aws
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Building the .NET 4.6.1 application...
      - msbuild /p:Configuration=Release
      - echo Dockerizing the .NET 4.6.1 application...
      - docker build -t $ECR_REPO_NAME:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
      - echo Build completed
