using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Tipstaff.MemoryCollections
{
    public class Country
    {
        public int CountryID { get; set; }

        public string Detail { get; set; }

        public int Active { get; set; }
   }

    public class CountryList
    {
        public static List<Country> GetCountryList()
        {
            return new List<Country>()
            {
                new Country() { CountryID=1, Detail="Afghanistan", Active=1},
                new Country() { CountryID=2, Detail="Akrotiri", Active=1},
                new Country() { CountryID=3, Detail="Albania", Active=1},
                new Country() { CountryID=4, Detail="Algeria", Active=1},
                new Country() { CountryID=5, Detail="American Samoa", Active=1},
                new Country() { CountryID=6, Detail="Andorra", Active=1},
                new Country() { CountryID=7, Detail="Angola", Active=1},
                new Country() { CountryID=8, Detail="Anguilla", Active=1},
                new Country() { CountryID=9, Detail="Antarctica", Active=1},
                new Country() { CountryID=10, Detail="Antigua and Barbuda", Active=1},
                new Country() { CountryID=11, Detail="Arctic Ocean", Active=1},
                new Country() { CountryID=12, Detail="Argentina", Active=1},
                new Country() { CountryID=13, Detail="Armenia", Active=1},
                new Country() { CountryID=14, Detail="Aruba", Active=1},
                new Country() { CountryID=15, Detail="Ashmore and Cartier Islands", Active=1},
                new Country() { CountryID=16, Detail="Atlantic Ocean", Active=1},
                new Country() { CountryID=17, Detail="Australia", Active=1},
                new Country() { CountryID=18, Detail="Austria", Active=1},
                new Country() { CountryID=19, Detail="Azerbaijan", Active=1},
                new Country() { CountryID=20, Detail="Bahamas, The", Active=1},
                new Country() { CountryID=21, Detail="Bahrain", Active=1},
                new Country() { CountryID=22, Detail="Bangladesh", Active=1},
                new Country() { CountryID=23, Detail="Barbados", Active=1},
                new Country() { CountryID=24, Detail="Belarus", Active=1},
                new Country() { CountryID=25, Detail="Belgium", Active=1},
                new Country() { CountryID=26, Detail="Belize", Active=1},
                new Country() { CountryID=27, Detail="Benin", Active=1},
                new Country() { CountryID=28, Detail="Bermuda", Active=1},
                new Country() { CountryID=29, Detail="Bhutan", Active=1},
                new Country() { CountryID=30, Detail="Bolivia", Active=1},
                new Country() { CountryID=31, Detail="Bosnia and Herzegovina", Active=1},
                new Country() { CountryID=32, Detail="Botswana", Active=1},
                new Country() { CountryID=33, Detail="Bouvet Island", Active=1},
                new Country() { CountryID=34, Detail="Brazil", Active=1},
                new Country() { CountryID=35, Detail="British Indian Ocean Territory", Active=1},
                new Country() { CountryID=36, Detail="British Virgin Islands", Active=1},
                new Country() { CountryID=37, Detail="Brunei", Active=1},
                new Country() { CountryID=38, Detail="Bulgaria", Active=1},
                new Country() { CountryID=39, Detail="Burkina Faso", Active=1},
                new Country() { CountryID=40, Detail="Burma", Active=1},
                new Country() { CountryID=41, Detail="Burundi", Active=1},
                new Country() { CountryID=42, Detail="Cambodia", Active=1},
                new Country() { CountryID=43, Detail="Cameroon", Active=1},
                new Country() { CountryID=44, Detail="Canada", Active=1},
                new Country() { CountryID=45, Detail="Cape Verde", Active=1},
                new Country() { CountryID=46, Detail="Cayman Islands", Active=1},
                new Country() { CountryID=47, Detail="Central African Republic", Active=1},
                new Country() { CountryID=48, Detail="Chad 2", Active=1},
                new Country() { CountryID=49, Detail="Chile", Active=1},
                new Country() { CountryID=50, Detail="China", Active=1},
                new Country() { CountryID=51, Detail="Christmas Island", Active=1},
                new Country() { CountryID=52, Detail="Clipperton Island", Active=1},
                new Country() { CountryID=53, Detail="Cocos (Keeling) Islands", Active=1},
                new Country() { CountryID=54, Detail="Colombia", Active=1},
                new Country() { CountryID=55, Detail="Comoros", Active=1},
                new Country() { CountryID=56, Detail="Congo, Democratic Republic of the", Active=1},
                new Country() { CountryID=57, Detail="Congo, Republic of the", Active=1},
                new Country() { CountryID=58, Detail="Cook Islands", Active=1},
                new Country() { CountryID=59, Detail="Coral Sea Islands", Active=1},
                new Country() { CountryID=60, Detail="Costa Rica", Active=1},
                new Country() { CountryID=61, Detail="Cote d'Ivoire", Active=1},
                new Country() { CountryID=62, Detail="Croatia", Active=1},
                new Country() { CountryID=63, Detail="Cuba", Active=1},
                new Country() { CountryID=64, Detail="Curacao", Active=1},
                new Country() { CountryID=65, Detail="Cyprus", Active=1},
                new Country() { CountryID=66, Detail="Czech Republic", Active=1},
                new Country() { CountryID=67, Detail="Denmark", Active=1},
                new Country() { CountryID=68, Detail="Dhekelia", Active=1},
                new Country() { CountryID=69, Detail="Djibouti", Active=1},
                new Country() { CountryID=70, Detail="Dominica", Active=1},
                new Country() { CountryID=71, Detail="Dominican Republic", Active=1},
                new Country() { CountryID=72, Detail="Ecuador", Active=1},
                new Country() { CountryID=73, Detail="Egypt", Active=1},
                new Country() { CountryID=74, Detail="El Salvador", Active=1},
                new Country() { CountryID=75, Detail="Equatorial Guinea", Active=1},
                new Country() { CountryID=76, Detail="Eritrea", Active=1},
                new Country() { CountryID=77, Detail="Estonia", Active=1},
                new Country() { CountryID=78, Detail="Ethiopia", Active=1},
                new Country() { CountryID=79, Detail="Falkland Islands (Islas Malvinas)", Active=1},
                new Country() { CountryID=80, Detail="Faroe Islands", Active=1},
                new Country() { CountryID=81, Detail="Fiji", Active=1},
                new Country() { CountryID=82, Detail="Finland", Active=1},
                new Country() { CountryID=83, Detail="France", Active=1},
                new Country() { CountryID=84, Detail="French Polynesia", Active=1},
                new Country() { CountryID=85, Detail="French Southern and Antarctic Lands", Active=1},
                new Country() { CountryID=86, Detail="Gabon", Active=1},
                new Country() { CountryID=87, Detail="Gambia, The", Active=1},
                new Country() { CountryID=88, Detail="Gaza Strip", Active=1},
                new Country() { CountryID=89, Detail="Georgia", Active=1},
                new Country() { CountryID=90, Detail="Germany", Active=1},
                new Country() { CountryID=91, Detail="Ghana", Active=1},
                new Country() { CountryID=92, Detail="Gibraltar", Active=1},
                new Country() { CountryID=93, Detail="Greece", Active=1},
                new Country() { CountryID=94, Detail="Greenland", Active=1},
                new Country() { CountryID=95, Detail="Grenada", Active=1},
                new Country() { CountryID=96, Detail="Guam", Active=1},
                new Country() { CountryID=97, Detail="Guatemala", Active=1},
                new Country() { CountryID=98, Detail="Guernsey", Active=1},
                new Country() { CountryID=99, Detail="Guinea", Active=1},
                new Country() { CountryID=100, Detail="Guinea-Bissau", Active=1},
                new Country() { CountryID=101, Detail="Guyana", Active=1},
                new Country() { CountryID=102, Detail="Haiti", Active=1},
                new Country() { CountryID=103, Detail="Heard Island and McDonald Islands", Active=1},
                new Country() { CountryID=104, Detail="Holy See (Vatican City)", Active=1},
                new Country() { CountryID=105, Detail="Honduras", Active=1},
                new Country() { CountryID=106, Detail="Hong Kong", Active=1},
                new Country() { CountryID=107, Detail="Hungary", Active=1},
                new Country() { CountryID=108, Detail="Iceland", Active=1},
                new Country() { CountryID=109, Detail="India", Active=1},
                new Country() { CountryID=110, Detail="Indian Ocean", Active=1},
                new Country() { CountryID=111, Detail="Indonesia", Active=1},
                new Country() { CountryID=112, Detail="Iran", Active=1},
                new Country() { CountryID=113, Detail="Iraq", Active=1},
                new Country() { CountryID=114, Detail="Ireland", Active=1},
                new Country() { CountryID=115, Detail="Isle of Man", Active=1},
                new Country() { CountryID=116, Detail="Israel", Active=1},
                new Country() { CountryID=117, Detail="Italy", Active=1},
                new Country() { CountryID=118, Detail="Jamaica", Active=1},
                new Country() { CountryID=119, Detail="Jan Mayen", Active=1},
                new Country() { CountryID=120, Detail="Japan", Active=1},
                new Country() { CountryID=121, Detail="Jersey", Active=1},
                new Country() { CountryID=122, Detail="Jordan", Active=1},
                new Country() { CountryID=123, Detail="Kazakhstan", Active=1},
                new Country() { CountryID=124, Detail="Kenya", Active=1},
                new Country() { CountryID=125, Detail="Kiribati", Active=1},
                new Country() { CountryID=126, Detail="Korea, North", Active=1},
                new Country() { CountryID=127, Detail="Korea, South", Active=1},
                new Country() { CountryID=128, Detail="Kosovo", Active=1},
                new Country() { CountryID=129, Detail="Kuwait", Active=1},
                new Country() { CountryID=130, Detail="Kyrgyzstan", Active=1},
                new Country() { CountryID=131, Detail="Laos", Active=1},
                new Country() { CountryID=132, Detail="Latvia", Active=1},
                new Country() { CountryID=133, Detail="Lebanon", Active=1},
                new Country() { CountryID=134, Detail="Lesotho", Active=1},
                new Country() { CountryID=135, Detail="Liberia", Active=1},
                new Country() { CountryID=136, Detail="Libya", Active=1},
                new Country() { CountryID=137, Detail="Liechtenstein", Active=1},
                new Country() { CountryID=138, Detail="Lithuania", Active=1},
                new Country() { CountryID=139, Detail="Luxembourg", Active=1},
                new Country() { CountryID=140, Detail="Macau", Active=1},
                new Country() { CountryID=141, Detail="Macedonia", Active=1},
                new Country() { CountryID=142, Detail="Madagascar", Active=1},
                new Country() { CountryID=143, Detail="Malawi", Active=1},
                new Country() { CountryID=144, Detail="Malaysia", Active=1},
                new Country() { CountryID=145, Detail="Maldives", Active=1},
                new Country() { CountryID=146, Detail="Mali", Active=1},
                new Country() { CountryID=147, Detail="Malta", Active=1},
                new Country() { CountryID=148, Detail="Marshall Islands", Active=1},
                new Country() { CountryID=149, Detail="Mauritania", Active=1},
                new Country() { CountryID=150, Detail="Mauritius", Active=1},
                new Country() { CountryID=151, Detail="Mexico", Active=1},
                new Country() { CountryID=152, Detail="Micronesia, Federated States of", Active=1},
                new Country() { CountryID=153, Detail="Moldova", Active=1},
                new Country() { CountryID=154, Detail="Monaco", Active=1},
                new Country() { CountryID=155, Detail="Mongolia", Active=1},
                new Country() { CountryID=156, Detail="Montenegro", Active=1},
                new Country() { CountryID=157, Detail="Montserrat", Active=1},
                new Country() { CountryID=158, Detail="Morocco", Active=1},
                new Country() { CountryID=159, Detail="Mozambique", Active=1},
                new Country() { CountryID=160, Detail="Namibia", Active=1},
                new Country() { CountryID=161, Detail="Nauru", Active=1},
                new Country() { CountryID=162, Detail="Navassa Island", Active=1},
                new Country() { CountryID=163, Detail="Nepal", Active=1},
                new Country() { CountryID=164, Detail="Netherlands", Active=1},
                new Country() { CountryID=165, Detail="New Caledonia", Active=1},
                new Country() { CountryID=166, Detail="New Zealand", Active=1},
                new Country() { CountryID=167, Detail="Nicaragua", Active=1},
                new Country() { CountryID=168, Detail="Niger", Active=1},
                new Country() { CountryID=169, Detail="Nigeria", Active=1},
                new Country() { CountryID=170, Detail="Niue", Active=1},
                new Country() { CountryID=171, Detail="Norfolk Island", Active=1},
                new Country() { CountryID=172, Detail="Northern Mariana Islands", Active=1},
                new Country() { CountryID=173, Detail="Norway", Active=1},
                new Country() { CountryID=174, Detail="Oman", Active=1},
                new Country() { CountryID=175, Detail="Pacific Ocean", Active=1},
                new Country() { CountryID=176, Detail="Pakistan", Active=1},
                new Country() { CountryID=177, Detail="Palau", Active=1},
                new Country() { CountryID=178, Detail="Panama", Active=1},
                new Country() { CountryID=179, Detail="Papua New Guinea", Active=1},
                new Country() { CountryID=180, Detail="Paracel Islands", Active=1},
                new Country() { CountryID=181, Detail="Paraguay", Active=1},
                new Country() { CountryID=182, Detail="Peru", Active=1},
                new Country() { CountryID=183, Detail="Philippines", Active=1},
                new Country() { CountryID=184, Detail="Pitcairn Islands", Active=1},
                new Country() { CountryID=185, Detail="Poland", Active=1},
                new Country() { CountryID=186, Detail="Portugal", Active=1},
                new Country() { CountryID=187, Detail="Puerto Rico", Active=1},
                new Country() { CountryID=188, Detail="Qatar", Active=1},
                new Country() { CountryID=189, Detail="Romania", Active=1},
                new Country() { CountryID=190, Detail="Russia", Active=1},
                new Country() { CountryID=191, Detail="Rwanda", Active=1},
                new Country() { CountryID=192, Detail="Saint Barthelemy", Active=1},
                new Country() { CountryID=193, Detail="Saint Helena, Ascension, and Tristan da Cunha", Active=1},
                new Country() { CountryID=194, Detail="Saint Kitts and Nevis", Active=1},
                new Country() { CountryID=195, Detail="Saint Lucia", Active=1},
                new Country() { CountryID=196, Detail="Saint Martin", Active=1},
                new Country() { CountryID=197, Detail="Saint Pierre and Miquelon", Active=1},
                new Country() { CountryID=198, Detail="Saint Vincent and the Grenadines", Active=1},
                new Country() { CountryID=199, Detail="Samoa", Active=1},
                new Country() { CountryID=200, Detail="San Marino", Active=1},
                new Country() { CountryID=201, Detail="Sao Tome and Principe", Active=1},
                new Country() { CountryID=202, Detail="Saudi Arabia", Active=1},
                new Country() { CountryID=203, Detail="Senegal", Active=1},
                new Country() { CountryID=204, Detail="Serbia", Active=1},
                new Country() { CountryID=205, Detail="Seychelles", Active=1},
                new Country() { CountryID=206, Detail="Sierra Leone", Active=1},
                new Country() { CountryID=207, Detail="Singapore", Active=1},
                new Country() { CountryID=208, Detail="Sint Maarten", Active=1},
                new Country() { CountryID=209, Detail="Slovakia", Active=1},
                new Country() { CountryID=210, Detail="Slovenia", Active=1},
                new Country() { CountryID=211, Detail="Solomon Islands", Active=1},
                new Country() { CountryID=212, Detail="Somalia", Active=1},
                new Country() { CountryID=213, Detail="South Africa", Active=1},
                new Country() { CountryID=214, Detail="South Georgia and South Sandwich Islands", Active=1},
                new Country() { CountryID=215, Detail="Southern Ocean", Active=1},
                new Country() { CountryID=216, Detail="South Sudan", Active=1},
                new Country() { CountryID=217, Detail="Spain", Active=1},
                new Country() { CountryID=218, Detail="Spratly Islands", Active=1},
                new Country() { CountryID=219, Detail="Sri Lanka", Active=1},
                new Country() { CountryID=220, Detail="Sudan", Active=1},
                new Country() { CountryID=221, Detail="Suriname", Active=1},
                new Country() { CountryID=222, Detail="Svalbard", Active=1},
                new Country() { CountryID=223, Detail="Swaziland", Active=1},
                new Country() { CountryID=224, Detail="Sweden", Active=1},
                new Country() { CountryID=225, Detail="Switzerland", Active=1},
                new Country() { CountryID=226, Detail="Syria", Active=1},
                new Country() { CountryID=227, Detail="Taiwan", Active=1},
                new Country() { CountryID=228, Detail="Tajikistan", Active=1},
                new Country() { CountryID=229, Detail="Tanzania", Active=1},
                new Country() { CountryID=230, Detail="Thailand", Active=1},
                new Country() { CountryID=231, Detail="Timor-Leste", Active=1},
                new Country() { CountryID=232, Detail="Togo", Active=1},
                new Country() { CountryID=233, Detail="Tokelau", Active=1},
                new Country() { CountryID=234, Detail="Tonga", Active=1},
                new Country() { CountryID=235, Detail="Trinidad and Tobago", Active=1},
                new Country() { CountryID=236, Detail="Tunisia", Active=1},
                new Country() { CountryID=237, Detail="Turkey", Active=1},
                new Country() { CountryID=238, Detail="Turkmenistan", Active=1},
                new Country() { CountryID=239, Detail="Turks and Caicos Islands", Active=1},
                new Country() { CountryID=240, Detail="Tuvalu", Active=1},
                new Country() { CountryID=241, Detail="Uganda", Active=1},
                new Country() { CountryID=242, Detail="Ukraine", Active=1},
                new Country() { CountryID=243, Detail="United Arab Emirates", Active=1},
                new Country() { CountryID=244, Detail="United Kingdom", Active=1},
                new Country() { CountryID=245, Detail="United States", Active=1},
                new Country() { CountryID=246, Detail="United States Pacific Island Wildlife Refuges", Active=1},
                new Country() { CountryID=247, Detail="Uruguay", Active=1},
                new Country() { CountryID=248, Detail="Uzbekistan", Active=1},
                new Country() { CountryID=249, Detail="Vanuatu", Active=1},
                new Country() { CountryID=250, Detail="Venezuela", Active=1},
                new Country() { CountryID=251, Detail="Vietnam", Active=1},
                new Country() { CountryID=252, Detail="Virgin Islands", Active=1},
                new Country() { CountryID=253, Detail="Wake Island", Active=1},
                new Country() { CountryID=254, Detail="Wallis and Futuna", Active=1},
                new Country() { CountryID=255, Detail="West Bank", Active=1},
                new Country() { CountryID=256, Detail="Western Sahara", Active=1},
                new Country() { CountryID=257, Detail="Yemen", Active=1},
                new Country() { CountryID=258, Detail="Zambia", Active=1},
                new Country() { CountryID=259, Detail="Zimbabwe", Active=1},
                new Country() { CountryID=260, Detail="European Union", Active=1},
                new Country() { CountryID=261, Detail="Not Applicable", Active=1},
                new Country() { CountryID=262, Detail="Not Provided", Active=1},
                new Country() { CountryID=263, Detail="Not Known", Active=1},
                new Country() { CountryID=264, Detail="SP test", Active=0}
            };
        }

        public static Country GetCountryByDetail(string c)
        {
            return GetCountryList().Where(x => x.Detail == c).FirstOrDefault();
        }

        public static Country GetCountryByID(int id)
        {
            return GetCountryList().Where(x => x.CountryID == id).FirstOrDefault();
        }
    }
}