using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Tipstaff.MemoryCollections
{
    public class DocumentType
    {
        public int DocumentTypeID { get; set; }

        public string Detail { get; set; }

        public int Active { get; set; }
   }

    public class DocumentTypeList
    {
        public static List<DocumentType> GetDocumentTypeList()
        {
            return new List<DocumentType>()
            {
                new DocumentType() { DocumentTypeID=1, Detail="Generated", Active=0},
                new DocumentType() { DocumentTypeID=2, Detail="Order", Active=0},
                new DocumentType() { DocumentTypeID=3, Detail="Passport", Active=0},
                new DocumentType() { DocumentTypeID=4, Detail="Driving Licence", Active=0},
                new DocumentType() { DocumentTypeID=5, Detail="ID Card", Active=0},
                new DocumentType() { DocumentTypeID=6, Detail="SCD26 papers", Active=0},
                new DocumentType() { DocumentTypeID=7, Detail="Updated document", Active=0},
                new DocumentType() { DocumentTypeID=8, Detail="Other", Active=0},
                new DocumentType() { DocumentTypeID=9, Detail="Order to Solicitors Letter", Active=0},
                new DocumentType() { DocumentTypeID=10, Detail="Sol Info Sheet", Active=0},
                new DocumentType() { DocumentTypeID=11, Detail="Confirmation of Service Doc", Active=0},
                new DocumentType() { DocumentTypeID=12, Detail="File Review Letter 1 ", Active=0},
                new DocumentType() { DocumentTypeID=13, Detail="SCD 26 Cancellation", Active=0},
                new DocumentType() { DocumentTypeID=14, Detail="NPO Cancellation", Active=0},
                new DocumentType() { DocumentTypeID=15, Detail="Location Confirmation Letter", Active=0},
                new DocumentType() { DocumentTypeID=16, Detail="Collection Confirmation Letter", Active=0},
                new DocumentType() { DocumentTypeID=17, Detail="Passport Confirmation Letter", Active=0},
                new DocumentType() { DocumentTypeID=18, Detail="Final Order", Active=0},
                new DocumentType() { DocumentTypeID=19, Detail="NBTC Movement Request", Active=0},
                new DocumentType() { DocumentTypeID=20, Detail="File Review Letter 2", Active=0},
                new DocumentType() { DocumentTypeID=21, Detail="Warrant of Committal", Active=0},
                new DocumentType() { DocumentTypeID=22, Detail="Arrest Requests", Active=0},
                new DocumentType() { DocumentTypeID=23, Detail="Warrant of Arrest", Active=0},
                new DocumentType() { DocumentTypeID=24, Detail="Arrest Confirmation", Active=0},
                new DocumentType() { DocumentTypeID=25, Detail="PNC Circulation Request", Active=0},
                new DocumentType() { DocumentTypeID=26, Detail="Continuation Order", Active=0},
                new DocumentType() { DocumentTypeID=27, Detail="File Review Solicitors Reply", Active=0},
                new DocumentType() { DocumentTypeID=28, Detail="Location Order Form 1a", Active=0},
                new DocumentType() { DocumentTypeID=29, Detail="Location Order Form 1b", Active=0},
                new DocumentType() { DocumentTypeID=30, Detail="Collection Order Form 2a", Active=0},
                new DocumentType() { DocumentTypeID=31, Detail="Collection Order Form 2b", Active=0},
                new DocumentType() { DocumentTypeID=32, Detail="Passport Seizure Order Form 3a", Active=0},
                new DocumentType() { DocumentTypeID=33, Detail="Passport Seizure Order Form 3b", Active=0},
                new DocumentType() { DocumentTypeID=34, Detail="Solicitors Undertakings", Active=0},
                new DocumentType() { DocumentTypeID=35, Detail="Passport", Active=0},
                new DocumentType() { DocumentTypeID=36, Detail="Birth Certificate", Active=0},
                new DocumentType() { DocumentTypeID=37, Detail="ID Card", Active=0},
                new DocumentType() { DocumentTypeID=38, Detail="Application to Discharge Order", Active=0},
                new DocumentType() { DocumentTypeID=39, Detail="NBTC Movement Request Result", Active=0},
                new DocumentType() { DocumentTypeID=40, Detail="Notice (Form 5b)", Active=0},
                new DocumentType() { DocumentTypeID=41, Detail="Police Report", Active=0},
                new DocumentType() { DocumentTypeID=42, Detail="Photograph", Active=0},
                new DocumentType() { DocumentTypeID=43, Detail="SCD 26 Papers", Active=0},
                new DocumentType() { DocumentTypeID=44, Detail="Correspondence Out", Active=0},
                new DocumentType() { DocumentTypeID=45, Detail="Correspondence In", Active=0},
                new DocumentType() { DocumentTypeID=46, Detail="NBTC Alert", Active=0},
                new DocumentType() { DocumentTypeID=47, Detail="Passport Return Receipt", Active=0},
                new DocumentType() { DocumentTypeID=48, Detail="Statement", Active=0},
                new DocumentType() { DocumentTypeID=49, Detail="Expiry Notification Letter", Active=0},
                new DocumentType() { DocumentTypeID=50, Detail="Bail Order", Active=0},
                new DocumentType() { DocumentTypeID=51, Detail="Remand Order", Active=0},
                new DocumentType() { DocumentTypeID=52, Detail="File Review Sols Reply (Letter)", Active=0},
                new DocumentType() { DocumentTypeID=53, Detail="File Review Sols Reply (E-mail)", Active=0},
                new DocumentType() { DocumentTypeID=54, Detail="E-mail", Active=0},
                new DocumentType() { DocumentTypeID=55, Detail="File Review (E-mail)", Active=0},
                new DocumentType() { DocumentTypeID=56, Detail="E-Mail SCD 26 Circulation Req", Active=0},
                new DocumentType() { DocumentTypeID=57, Detail="E-Mail NPO Port Alert Req", Active=0},
                new DocumentType() { DocumentTypeID=58, Detail="E-Mail (Order to Solicitors)", Active=0},
                new DocumentType() { DocumentTypeID=59, Detail="E-Mail (SCD 26 Cancellation)", Active=0},
                new DocumentType() { DocumentTypeID=60, Detail="E-Mail NPO Cancellation)", Active=0},
                new DocumentType() { DocumentTypeID=61, Detail="E-Mail Police Execution Request", Active=0},
                new DocumentType() { DocumentTypeID=62, Detail="E-Mail (Police CAD or Force Reference Number)", Active=0},
                new DocumentType() { DocumentTypeID=63, Detail="E-Mail File Review Sols Reply", Active=0},
                new DocumentType() { DocumentTypeID=64, Detail="E-Mail Arrest Request", Active=0},
                new DocumentType() { DocumentTypeID=65, Detail="E-Mail NBTC Movement Request", Active=0},
                new DocumentType() { DocumentTypeID=66, Detail="E-Mail (Port Intercept Request)", Active=0},
                new DocumentType() { DocumentTypeID=67, Detail="E-Mail (Address Check Result)", Active=0},
                new DocumentType() { DocumentTypeID=68, Detail="E-Mail (Confirmation of Service to Sols)", Active=0},
                new DocumentType() { DocumentTypeID=69, Detail="E-Mail (NBTC Movement Check Result)", Active=0},
                new DocumentType() { DocumentTypeID=70, Detail="E-Mail (Advise OR Warrant Active )", Active=0},
                new DocumentType() { DocumentTypeID=71, Detail="Warrant of Committal 6c", Active=0},
                new DocumentType() { DocumentTypeID=72, Detail="Order for Immediate Committal 6a", Active=0},
                new DocumentType() { DocumentTypeID=73, Detail="E-Mail (File Review to Sols)", Active=0},
                new DocumentType() { DocumentTypeID=74, Detail="Tipstaff Report", Active=0},
                new DocumentType() { DocumentTypeID=75, Detail="Undertakings", Active=0},
                new DocumentType() { DocumentTypeID=76, Detail="Order for Discharge", Active=0},
                new DocumentType() { DocumentTypeID=77, Detail="Draft Order", Active=0},
                new DocumentType() { DocumentTypeID=78, Detail="Passport Return Letter", Active=0},
                new DocumentType() { DocumentTypeID=79, Detail="Flight Itinerary", Active=0},
                new DocumentType() { DocumentTypeID=80, Detail="Passport Release Form", Active=0},
                new DocumentType() { DocumentTypeID=81, Detail="Release From Custody Order", Active=0},
                new DocumentType() { DocumentTypeID=82, Detail="DWP Disclosure", Active=0},
                new DocumentType() { DocumentTypeID=83, Detail="Dept of Education Disclosure", Active=0},
                new DocumentType() { DocumentTypeID=84, Detail="HMR&C Disclosure", Active=0},
                new DocumentType() { DocumentTypeID=85, Detail="NHS Disclosure", Active=0},
                new DocumentType() { DocumentTypeID=86, Detail="Local Authority Disclosure", Active=0},
                new DocumentType() { DocumentTypeID=87, Detail="Police Disclosure", Active=0},
                new DocumentType() { DocumentTypeID=88, Detail="E-Mail Address Check Request", Active=0},
                new DocumentType() { DocumentTypeID=89, Detail="SCD 26 Warrant Circulation Request", Active=0},
                new DocumentType() { DocumentTypeID=90, Detail="NPO Port Alert Request", Active=0},
                new DocumentType() { DocumentTypeID=91, Detail="E-mail PNC Vehicle Index Check Result", Active=0},
                new DocumentType() { DocumentTypeID=92, Detail="NBTC PIW Request", Active=0},
                new DocumentType() { DocumentTypeID=93, Detail="NBTC RFI Request", Active=0},
                new DocumentType() { DocumentTypeID=94, Detail="NBTC RFI Result", Active=0},
                new DocumentType() { DocumentTypeID=95, Detail="E-Mail (NBTC PIW Request)", Active=0},
                new DocumentType() { DocumentTypeID=96, Detail="E-Mail (NBTC RFI Request)", Active=0},
                new DocumentType() { DocumentTypeID=97, Detail="E-Mail (NBTC RFI Result)", Active=0},
                new DocumentType() { DocumentTypeID=98, Detail="E-Mail (PNC ID Numbers)", Active=0},
                new DocumentType() { DocumentTypeID=99, Detail="E-Mail (NPO Ref Number)", Active=0},
                new DocumentType() { DocumentTypeID=100, Detail="E-Mail (NBTC Alert)", Active=0},
                new DocumentType() { DocumentTypeID=101, Detail="Warrant of Committal", Active=0},
                new DocumentType() { DocumentTypeID=102, Detail="E-Mail (Arrest Notification OR)", Active=0},
                new DocumentType() { DocumentTypeID=103, Detail="E-Mail (Arest Notification Companied Court)", Active=0},
                new DocumentType() { DocumentTypeID=104, Detail="E-Mail (Police Ref Number)", Active=0},
                new DocumentType() { DocumentTypeID=105, Detail="Arrest Confirmation", Active=0},
                new DocumentType() { DocumentTypeID=106, Detail="Arrest Request", Active=0},
                new DocumentType() { DocumentTypeID=107, Detail="Birth Certificate", Active=0},
                new DocumentType() { DocumentTypeID=108, Detail="Cancellation SCD 26 Location", Active=0},
                new DocumentType() { DocumentTypeID=109, Detail="Cancellation SCD 26 Collection", Active=0},
                new DocumentType() { DocumentTypeID=110, Detail="Cancellation SCD 26 Passport Seizure", Active=0},
                new DocumentType() { DocumentTypeID=111, Detail="Cancellation SCD 26 Warrant", Active=0},
                new DocumentType() { DocumentTypeID=112, Detail="Cancellation NPO Location", Active=0},
                new DocumentType() { DocumentTypeID=113, Detail="Cancellation NPO Collection", Active=0},
                new DocumentType() { DocumentTypeID=114, Detail="Cancellation NPO Passport Seizure", Active=0},
                new DocumentType() { DocumentTypeID=115, Detail="Cancellation NPO Warrant", Active=0},
                new DocumentType() { DocumentTypeID=116, Detail="Confirmation of Service", Active=0},
                new DocumentType() { DocumentTypeID=117, Detail="Correspondence In", Active=0},
                new DocumentType() { DocumentTypeID=118, Detail="Correspondence Out", Active=0},
                new DocumentType() { DocumentTypeID=119, Detail="Debtor / Contemnor Info Sheet", Active=0},
                new DocumentType() { DocumentTypeID=120, Detail="Disclosure Dept of Education", Active=0},
                new DocumentType() { DocumentTypeID=121, Detail="Disclosure NHS", Active=0},
                new DocumentType() { DocumentTypeID=122, Detail="Disclosure Local Authority", Active=0},
                new DocumentType() { DocumentTypeID=123, Detail="Disclosure HMR&C", Active=0},
                new DocumentType() { DocumentTypeID=124, Detail="Disclosure Police", Active=0},
                new DocumentType() { DocumentTypeID=125, Detail="Disclosure Solicitors", Active=0},
                new DocumentType() { DocumentTypeID=126, Detail="Disclosure Women's Refuge", Active=0},
                new DocumentType() { DocumentTypeID=127, Detail="Driving Licence", Active=0},
                new DocumentType() { DocumentTypeID=128, Detail="E-Ticket", Active=0},
                new DocumentType() { DocumentTypeID=129, Detail="Expiry Notification Location", Active=0},
                new DocumentType() { DocumentTypeID=130, Detail="Expiry Notification Collection", Active=0},
                new DocumentType() { DocumentTypeID=131, Detail="Expiry Notification Passport Seizure", Active=0},
                new DocumentType() { DocumentTypeID=132, Detail="Expiry Notification Warrant", Active=0},
                new DocumentType() { DocumentTypeID=133, Detail="File Review Location", Active=0},
                new DocumentType() { DocumentTypeID=134, Detail="File Review Collection", Active=0},
                new DocumentType() { DocumentTypeID=135, Detail="File Review Passport Seizure", Active=0},
                new DocumentType() { DocumentTypeID=136, Detail="File Review Reply", Active=0},
                new DocumentType() { DocumentTypeID=137, Detail="ID Card", Active=0},
                new DocumentType() { DocumentTypeID=138, Detail="NBTC Alert", Active=0},
                new DocumentType() { DocumentTypeID=139, Detail="NBTC RFI", Active=0},
                new DocumentType() { DocumentTypeID=140, Detail="NBTC RFI Result", Active=0},
                new DocumentType() { DocumentTypeID=141, Detail="Order Location 1a", Active=0},
                new DocumentType() { DocumentTypeID=142, Detail="Order Location 1b", Active=0},
                new DocumentType() { DocumentTypeID=143, Detail="Order Collection 2a", Active=0},
                new DocumentType() { DocumentTypeID=144, Detail="Order Collection 2b", Active=0},
                new DocumentType() { DocumentTypeID=145, Detail="Order Passport Seizure 3a", Active=0},
                new DocumentType() { DocumentTypeID=146, Detail="Order Passport Seizure 3b", Active=0},
                new DocumentType() { DocumentTypeID=147, Detail="Order Directions", Active=0},
                new DocumentType() { DocumentTypeID=148, Detail="Order Draft", Active=0},
                new DocumentType() { DocumentTypeID=149, Detail="Order Final", Active=0},
                new DocumentType() { DocumentTypeID=150, Detail="Order of Committal", Active=0},
                new DocumentType() { DocumentTypeID=151, Detail="Order of Committal 6a", Active=0},
                new DocumentType() { DocumentTypeID=152, Detail="Order Release From Custody", Active=0},
                new DocumentType() { DocumentTypeID=153, Detail="Order Remand", Active=0},
                new DocumentType() { DocumentTypeID=154, Detail="Order to Sols Location", Active=0},
                new DocumentType() { DocumentTypeID=155, Detail="Order to Sols Collection", Active=0},
                new DocumentType() { DocumentTypeID=156, Detail="Order to Sols Passport Seizure", Active=0},
                new DocumentType() { DocumentTypeID=157, Detail="Passport", Active=0},
                new DocumentType() { DocumentTypeID=158, Detail="Passport Release Form", Active=0},
                new DocumentType() { DocumentTypeID=159, Detail="Passport Return Receipt Signed", Active=0},
                new DocumentType() { DocumentTypeID=160, Detail="Passport Return Receipt Unsigned", Active=0},
                new DocumentType() { DocumentTypeID=161, Detail="Photograph", Active=0},
                new DocumentType() { DocumentTypeID=162, Detail="Police Address Check Location", Active=0},
                new DocumentType() { DocumentTypeID=163, Detail="Police Address Check Collection", Active=0},
                new DocumentType() { DocumentTypeID=164, Detail="Police Address Check Passport Seizure", Active=0},
                new DocumentType() { DocumentTypeID=165, Detail="Report Police", Active=0},
                new DocumentType() { DocumentTypeID=166, Detail="Report Tipstaff", Active=0},
                new DocumentType() { DocumentTypeID=167, Detail="Solicitors Confirmation Letter Location", Active=0},
                new DocumentType() { DocumentTypeID=168, Detail="Solicitors Confirmation Letter Collection", Active=0},
                new DocumentType() { DocumentTypeID=169, Detail="Solicitors Confirmation Letter Passport Seizure", Active=0},
                new DocumentType() { DocumentTypeID=170, Detail="Solicitors Info Sheet", Active=0},
                new DocumentType() { DocumentTypeID=171, Detail="Statement of Arrest Police", Active=0},
                new DocumentType() { DocumentTypeID=172, Detail="Statement of Arrest Tipstaff", Active=0},
                new DocumentType() { DocumentTypeID=173, Detail="Travel Document", Active=0},
                new DocumentType() { DocumentTypeID=174, Detail="Warrant of Arrest", Active=0},
                new DocumentType() { DocumentTypeID=175, Detail="Warrant of Committal", Active=0},
                new DocumentType() { DocumentTypeID=176, Detail="Warrant of Committal 6C", Active=0},
                new DocumentType() { DocumentTypeID=177, Detail="E-Mail Notification of Arrest", Active=0},
                new DocumentType() { DocumentTypeID=178, Detail="E-Mail Person in Custody (Cells)", Active=0},
                new DocumentType() { DocumentTypeID=179, Detail="E-Mail Confirmation of Service", Active=0},
                new DocumentType() { DocumentTypeID=180, Detail="E-Mail Misc", Active=0},
                new DocumentType() { DocumentTypeID=181, Detail="E-Mail File Review", Active=0},
                new DocumentType() { DocumentTypeID=182, Detail="E-Mail NBTC Alert", Active=0},
                new DocumentType() { DocumentTypeID=183, Detail="E-Mail NBTC RFI", Active=0},
                new DocumentType() { DocumentTypeID=184, Detail="E-Mail NBTC RFI Result", Active=0},
                new DocumentType() { DocumentTypeID=185, Detail="E-Mail SCD 26 PNC Circulation Request", Active=0},
                new DocumentType() { DocumentTypeID=186, Detail="E-Mail SCD 26 PNC Cancellation", Active=0},
                new DocumentType() { DocumentTypeID=187, Detail="E-Mail SCD 26 Vehicle Index Check Request", Active=0},
                new DocumentType() { DocumentTypeID=188, Detail="E-Mail SCD 26 Vehicle Index Check Result", Active=0},
                new DocumentType() { DocumentTypeID=189, Detail="E-Mail SCD 26 PNC ID Numbers", Active=0},
                new DocumentType() { DocumentTypeID=190, Detail="E-Mail NPO Port Alert Request", Active=0},
                new DocumentType() { DocumentTypeID=191, Detail="E-Mail NPO Reference Number", Active=0},
                new DocumentType() { DocumentTypeID=192, Detail="E-Mail NPO Intercept Request Location", Active=0},
                new DocumentType() { DocumentTypeID=193, Detail="E-Mail NPO Intercept Request Collection", Active=0},
                new DocumentType() { DocumentTypeID=194, Detail="E-Mail NPO Intercept Request Passport Seizure", Active=0},
                new DocumentType() { DocumentTypeID=195, Detail="E-Mail Arrest Request", Active=0},
                new DocumentType() { DocumentTypeID=196, Detail="E-Mail Disclosure NHS", Active=0},
                new DocumentType() { DocumentTypeID=197, Detail="E-Mail Disclosure Local Authority", Active=0},
                new DocumentType() { DocumentTypeID=198, Detail="E-Mail Disclosure HMR&C", Active=0},
                new DocumentType() { DocumentTypeID=199, Detail="E-Mail Disclosure Police", Active=0},
                new DocumentType() { DocumentTypeID=200, Detail="E-Mail Disclosure Solicitiors", Active=0},
                new DocumentType() { DocumentTypeID=201, Detail="E-Mail Disclosure Women's Refuge", Active=0},
                new DocumentType() { DocumentTypeID=202, Detail="E-Mail Disclosure DWP", Active=0},
                new DocumentType() { DocumentTypeID=203, Detail="E-Mail Gatwick Intercept Request", Active=0},
                new DocumentType() { DocumentTypeID=204, Detail="E-Mail Gatwick Intercept Stansted", Active=0},
                new DocumentType() { DocumentTypeID=205, Detail="E-Mail Birmingham Intercept Request", Active=0},
                new DocumentType() { DocumentTypeID=206, Detail="E-Mail Luton Intercept Request", Active=0},
                new DocumentType() { DocumentTypeID=207, Detail="E-Mail Manchester Intercept Request", Active=0},
                new DocumentType() { DocumentTypeID=208, Detail="E-Mail Leeds Bradford Intercept Request", Active=0},
                new DocumentType() { DocumentTypeID=209, Detail="E-Mail Newcastle Intercept Request", Active=0},
                new DocumentType() { DocumentTypeID=210, Detail="E-Mail Expiry Notification Location", Active=0},
                new DocumentType() { DocumentTypeID=211, Detail="E-Mail Expiry Notification Collection", Active=0},
                new DocumentType() { DocumentTypeID=212, Detail="E-Mail Expiry Notification Passport Seizure", Active=0},
                new DocumentType() { DocumentTypeID=213, Detail="E-Mail Expiry Notification Warrant", Active=0},
                new DocumentType() { DocumentTypeID=214, Detail="E-Mail Sol Info Sheet", Active=0},
                new DocumentType() { DocumentTypeID=215, Detail="E-Mail Debtor / Contemnor Info Sheet", Active=0},
                new DocumentType() { DocumentTypeID=216, Detail="E-Mail Stansted Intercept Request", Active=0},
                new DocumentType() { DocumentTypeID=217, Detail="E-Mail SB Intercept Request Gatwick", Active=0},
                new DocumentType() { DocumentTypeID=218, Detail="E-Mail SB Intercept Request Luton", Active=0},
                new DocumentType() { DocumentTypeID=219, Detail="E-Mail SB Intercept Request Birmingham", Active=0},
                new DocumentType() { DocumentTypeID=220, Detail="E-Mail SB Intercept Request Manchester", Active=0},
                new DocumentType() { DocumentTypeID=221, Detail="E-Mail SB Intercept Request Leeds Bradford", Active=0},
                new DocumentType() { DocumentTypeID=222, Detail="E-Mail SB Intercept Request Newcastle", Active=0},
                new DocumentType() { DocumentTypeID=223, Detail="Disclosure DWP", Active=0},
                new DocumentType() { DocumentTypeID=224, Detail="E-Mail File Review Reply", Active=0},
                new DocumentType() { DocumentTypeID=225, Detail="E-Mail NPO Cancellation", Active=0},
                new DocumentType() { DocumentTypeID=226, Detail="SCD 26 Papers Location", Active=0},
                new DocumentType() { DocumentTypeID=227, Detail="SCD 26 Papers Collection", Active=0},
                new DocumentType() { DocumentTypeID=228, Detail="SCD 26 Papers Passport Seizure", Active=0},
                new DocumentType() { DocumentTypeID=229, Detail="E-Mail Order to Solicitors", Active=0},
                new DocumentType() { DocumentTypeID=230, Detail="E-Mail Police Address Check Request Locatio", Active=0},
                new DocumentType() { DocumentTypeID=231, Detail="E-Mail Police Address Check Request Collection", Active=0},
                new DocumentType() { DocumentTypeID=232, Detail="E-Mail Police Address Check Request Passport Seizure", Active=0},
                new DocumentType() { DocumentTypeID=233, Detail="E-Mail Police Address Check Request Location", Active=0},
                new DocumentType() { DocumentTypeID=234, Detail="E-Mail Police Force Reference Number", Active=0},
                new DocumentType() { DocumentTypeID=235, Detail="E-Mail Police Force Reference", Active=0},
                new DocumentType() { DocumentTypeID=236, Detail="E-Mail Intercept Request Stansted", Active=0},
                new DocumentType() { DocumentTypeID=237, Detail="Warrant of Arrest 5a", Active=0},
                new DocumentType() { DocumentTypeID=238, Detail="Notice 5b", Active=0},
                new DocumentType() { DocumentTypeID=239, Detail="Statement Tipstaff", Active=0},
                new DocumentType() { DocumentTypeID=240, Detail="SCD 26 PNC Circulation Request", Active=0},
                new DocumentType() { DocumentTypeID=241, Detail="Confirmation of Service (Pre Service)", Active=0},
                new DocumentType() { DocumentTypeID=242, Detail="Confirmation of Service (Completed)", Active=0},
                new DocumentType() { DocumentTypeID=243, Detail="Address Check Result (Solicitors)", Active=0},
                new DocumentType() { DocumentTypeID=244, Detail="Order Location", Active=0},
                new DocumentType() { DocumentTypeID=245, Detail="Order Location: Direction to Tipstaff", Active=0},
                new DocumentType() { DocumentTypeID=246, Detail="SSS-Ref & Vet Papers (Location)", Active=0},
                new DocumentType() { DocumentTypeID=247, Detail="UK Sirene Form G", Active=0},
                new DocumentType() { DocumentTypeID=248, Detail="Passport Order: Direction to Tipstaff", Active=0},
                new DocumentType() { DocumentTypeID=249, Detail="Passport Order", Active=0},
                new DocumentType() { DocumentTypeID=250, Detail="SSS-Ref & Vet Papers (Passport)", Active=0},
                new DocumentType() { DocumentTypeID=251, Detail="Collection Order", Active=0},
                new DocumentType() { DocumentTypeID=252, Detail="Collection Order: Direction to Tipstaff", Active=0},
                new DocumentType() { DocumentTypeID=253, Detail="SSS-Ref & Vet Papers (Collection)", Active=0},
                new DocumentType() { DocumentTypeID=254, Detail="Location Order", Active=0},
                new DocumentType() { DocumentTypeID=255, Detail="Location Order: Direction Tipstaff", Active=0},
                new DocumentType() { DocumentTypeID=256, Detail="Royal mail Confirmation of Delivery", Active=0},
                new DocumentType() { DocumentTypeID=257, Detail="Prohibited Steps Order", Active=0},
                new DocumentType() { DocumentTypeID=258, Detail="Intercept Request Bristol", Active=0},
                new DocumentType() { DocumentTypeID=259, Detail="Statutory Declarations", Active=0},
                new DocumentType() { DocumentTypeID=260, Detail="Misc Document", Active=0},
                new DocumentType() { DocumentTypeID=261, Detail="Report Social Worker", Active=0},
                new DocumentType() { DocumentTypeID=262, Detail="NPO Intercept Request", Active=0},
                new DocumentType() { DocumentTypeID=263, Detail="Confirmation of Arrest", Active=0},
                new DocumentType() { DocumentTypeID=264, Detail="Activation of Suspended Committal 6b", Active=0},
                new DocumentType() { DocumentTypeID=265, Detail="Address Check Result to Solicitor", Active=1},
                new DocumentType() { DocumentTypeID=266, Detail="Arrest Request", Active=1},
                new DocumentType() { DocumentTypeID=267, Detail="Birth Certificate", Active=1},
                new DocumentType() { DocumentTypeID=268, Detail="Cancellation Request NPO (Child Abduction)", Active=1},
                new DocumentType() { DocumentTypeID=269, Detail="Cancellation Request NPO (Warrant)", Active=1},
                new DocumentType() { DocumentTypeID=270, Detail="Cancellation Request SSS-Ref & Vet (Child Abduction)", Active=1},
                new DocumentType() { DocumentTypeID=271, Detail="Cancellation Request SSS-Ref & Vet (Warrant)", Active=1},
                new DocumentType() { DocumentTypeID=272, Detail="Collection Order Direction to the Tipstaff", Active=1},
                new DocumentType() { DocumentTypeID=273, Detail="Collection Order", Active=1},
                new DocumentType() { DocumentTypeID=274, Detail="C", Active=0},
                new DocumentType() { DocumentTypeID=275, Detail="Confirmation of Service (Pre Service)", Active=1},
                new DocumentType() { DocumentTypeID=276, Detail="Confirmation of Service (Post Service)", Active=1},
                new DocumentType() { DocumentTypeID=277, Detail="Confirmation of Arrest (Pre Arrest)", Active=1},
                new DocumentType() { DocumentTypeID=278, Detail="Confirmation of Arrest (Post Arrest)", Active=1},
                new DocumentType() { DocumentTypeID=279, Detail="Correspondence In", Active=1},
                new DocumentType() { DocumentTypeID=280, Detail="Correspondence Out", Active=1},
                new DocumentType() { DocumentTypeID=281, Detail="Disclosure DWP", Active=1},
                new DocumentType() { DocumentTypeID=282, Detail="Disclosure DoE", Active=1},
                new DocumentType() { DocumentTypeID=283, Detail="Disclosure HMR&C", Active=1},
                new DocumentType() { DocumentTypeID=284, Detail="Disclosure Local Authority", Active=1},
                new DocumentType() { DocumentTypeID=285, Detail="Disclosure NHS", Active=1},
                new DocumentType() { DocumentTypeID=286, Detail="Disclosure Police", Active=0},
                new DocumentType() { DocumentTypeID=287, Detail="Disclosure School", Active=1},
                new DocumentType() { DocumentTypeID=288, Detail="Disclosure Solicitor", Active=1},
                new DocumentType() { DocumentTypeID=289, Detail="Disclosure Police", Active=1},
                new DocumentType() { DocumentTypeID=290, Detail="Disclosure Women's Refuge", Active=1},
                new DocumentType() { DocumentTypeID=291, Detail="Driving Licence", Active=1},
                new DocumentType() { DocumentTypeID=292, Detail="E-Ticket", Active=1},
                new DocumentType() { DocumentTypeID=293, Detail="Expiry Notification Letter (Collection)", Active=1},
                new DocumentType() { DocumentTypeID=294, Detail="Expiry Notification Letter (Location)", Active=1},
                new DocumentType() { DocumentTypeID=295, Detail="Expiry Notification Letter (Passport)", Active=1},
                new DocumentType() { DocumentTypeID=296, Detail="Expiry Notification Letter (Warrant)", Active=1},
                new DocumentType() { DocumentTypeID=297, Detail="File Review Letter (Collection)", Active=1},
                new DocumentType() { DocumentTypeID=298, Detail="File Review Letter (Location)", Active=1},
                new DocumentType() { DocumentTypeID=299, Detail="File Review Letter (Passport)", Active=1},
                new DocumentType() { DocumentTypeID=300, Detail="File Review Letter (Warrant)", Active=1},
                new DocumentType() { DocumentTypeID=301, Detail="File Review Letter Reply (Collection)", Active=1},
                new DocumentType() { DocumentTypeID=302, Detail="File Review Letter Reply (Location)", Active=1},
                new DocumentType() { DocumentTypeID=303, Detail="File Review Letter Reply (Passport)", Active=1},
                new DocumentType() { DocumentTypeID=304, Detail="File Review Letter Reply (Warrant)", Active=1},
                new DocumentType() { DocumentTypeID=305, Detail="ID Card", Active=1},
                new DocumentType() { DocumentTypeID=306, Detail="Intercept Request (Birmingham Airport)", Active=1},
                new DocumentType() { DocumentTypeID=307, Detail="Intercept Request (Bristol Airport)", Active=1},
                new DocumentType() { DocumentTypeID=308, Detail="Intercept Request (Cardiff Airport)", Active=1},
                new DocumentType() { DocumentTypeID=309, Detail="Intercept Request (Exeter Airport)", Active=1},
                new DocumentType() { DocumentTypeID=310, Detail="Intercept Request (Gatwick Airport)", Active=1},
                new DocumentType() { DocumentTypeID=311, Detail="Intercept Request (Heathrow Airport)", Active=1},
                new DocumentType() { DocumentTypeID=312, Detail="Intercept Request (Leeds Airport)", Active=1},
                new DocumentType() { DocumentTypeID=313, Detail="Intercept Request (Luton Airport)", Active=1},
                new DocumentType() { DocumentTypeID=314, Detail="Intercept Request (Manchester Airport)", Active=1},
                new DocumentType() { DocumentTypeID=315, Detail="Intercept Request (Newcastle Airport)", Active=1},
                new DocumentType() { DocumentTypeID=316, Detail="Intercept Request (Stansted Airport)", Active=1},
                new DocumentType() { DocumentTypeID=317, Detail="Location Order", Active=1},
                new DocumentType() { DocumentTypeID=318, Detail="Location Order Direction to the Tipstaff", Active=1},
                new DocumentType() { DocumentTypeID=319, Detail="NBTC Alert", Active=1},
                new DocumentType() { DocumentTypeID=320, Detail="NBTC RFI", Active=1},
                new DocumentType() { DocumentTypeID=321, Detail="NBTC RFI Result", Active=1},
                new DocumentType() { DocumentTypeID=322, Detail="Notice 5b", Active=1},
                new DocumentType() { DocumentTypeID=323, Detail="Order Directions", Active=1},
                new DocumentType() { DocumentTypeID=324, Detail="Order Final", Active=1},
                new DocumentType() { DocumentTypeID=325, Detail="Order of Committal", Active=1},
                new DocumentType() { DocumentTypeID=326, Detail="Order of Committal 6b", Active=1},
                new DocumentType() { DocumentTypeID=327, Detail="Order Release From Custody", Active=1},
                new DocumentType() { DocumentTypeID=328, Detail="Order Remand", Active=1},
                new DocumentType() { DocumentTypeID=329, Detail="Order to Solicitors Letter (Collection)", Active=1},
                new DocumentType() { DocumentTypeID=330, Detail="Order to Solicitors Letter (Location)", Active=1},
                new DocumentType() { DocumentTypeID=331, Detail="Order to Solicitors Letter (Passport)", Active=1},
                new DocumentType() { DocumentTypeID=332, Detail="Passport Order", Active=1},
                new DocumentType() { DocumentTypeID=333, Detail="Passport Order Direction to the Tipstaff", Active=1},
                new DocumentType() { DocumentTypeID=334, Detail="Passport Return Receipt (Signed)", Active=1},
                new DocumentType() { DocumentTypeID=335, Detail="Passport Return Receipt (Unsigned)", Active=1},
                new DocumentType() { DocumentTypeID=336, Detail="Passport", Active=1},
                new DocumentType() { DocumentTypeID=337, Detail="Photograph", Active=1},
                new DocumentType() { DocumentTypeID=338, Detail="Police Address Check Request (Collection)", Active=1},
                new DocumentType() { DocumentTypeID=339, Detail="Police Address Check Request (Location)", Active=1},
                new DocumentType() { DocumentTypeID=340, Detail="Police Address Check Request (Passport)", Active=1},
                new DocumentType() { DocumentTypeID=341, Detail="Prohibited Steps Order", Active=1},
                new DocumentType() { DocumentTypeID=342, Detail="Report Police", Active=1},
                new DocumentType() { DocumentTypeID=343, Detail="Report Social Worker", Active=1},
                new DocumentType() { DocumentTypeID=344, Detail="Report Tipstaff", Active=1},
                new DocumentType() { DocumentTypeID=345, Detail="Royal Mail Confirmation of Delivery", Active=1},
                new DocumentType() { DocumentTypeID=346, Detail="SSS-Ref & Vet Papers (Collection)", Active=1},
                new DocumentType() { DocumentTypeID=347, Detail="SSS-Ref & Vet Papers (Location)", Active=1},
                new DocumentType() { DocumentTypeID=348, Detail="Statement of Arrest (Police)", Active=1},
                new DocumentType() { DocumentTypeID=349, Detail="Statement of Arrest (Tipstaff)", Active=1},
                new DocumentType() { DocumentTypeID=350, Detail="Travel Document", Active=1},
                new DocumentType() { DocumentTypeID=351, Detail="UK Sirene Bureau Form G", Active=1},
                new DocumentType() { DocumentTypeID=352, Detail="Warrant of Arrest", Active=1},
                new DocumentType() { DocumentTypeID=353, Detail="Warrant of Committal", Active=1},
                new DocumentType() { DocumentTypeID=354, Detail="Warrant of Committal 6c", Active=1},
                new DocumentType() { DocumentTypeID=355, Detail="Execution Confirmation Letter to Sol (Collection)", Active=1},
                new DocumentType() { DocumentTypeID=356, Detail="Execution Confirmation Letter to Sol (Location)", Active=1},
                new DocumentType() { DocumentTypeID=357, Detail="Execution Confirmation Letter to Sol (Passport)", Active=1},
                new DocumentType() { DocumentTypeID=358, Detail="Notice of Hearing", Active=1},
                new DocumentType() { DocumentTypeID=359, Detail="Solicitors Information Sheet (Child Abduction)", Active=1},
                new DocumentType() { DocumentTypeID=360, Detail="Solicitiors Information Sheet (Warrant)", Active=1},
                new DocumentType() { DocumentTypeID=361, Detail="SSS-Ref & Vet Papers (Passport) ", Active=1},
                new DocumentType() { DocumentTypeID=362, Detail="Residence Permit", Active=1},
                new DocumentType() { DocumentTypeID=363, Detail="Marriage Certificate", Active=1},
                new DocumentType() { DocumentTypeID=364, Detail="Deed Poll Name Change Document", Active=1},
                new DocumentType() { DocumentTypeID=365, Detail="Order Draft (Unsealed)", Active=1},
                new DocumentType() { DocumentTypeID=366, Detail="Execution Confirmation to Sols (Warrant)", Active=1},
                new DocumentType() { DocumentTypeID=367, Detail="Order FGM", Active=1},
                new DocumentType() { DocumentTypeID=368, Detail="B & I Arrested Persons Information", Active=1},
                new DocumentType() { DocumentTypeID=369, Detail="CH & QB Arrested Persons Information", Active=1},
                new DocumentType() { DocumentTypeID=370, Detail="Arrest Notification Letter Official Receiver", Active=1},
                new DocumentType() { DocumentTypeID=371, Detail="Warrant of Search & Seizure", Active=1}
            };
        }

        public static DocumentType GetDocumentTypeByDetail(string c)
        {
            return GetDocumentTypeList().FirstOrDefault(x => x.Detail == c);
        }

        public static DocumentType GetDocumentTypeByID(int id)
        {
            return GetDocumentTypeList().FirstOrDefault(x => x.DocumentTypeID == id);
        }
    }
}