using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Tipstaff.MemoryCollections
{
    public class Nationality
    {
        public int NationalityID { get; set; }

        public string Detail { get; set; }

        public int Active { get; set; }
   }

    public class NationalityList
    {
        public static List<Nationality> GetNationalityList()
        {
            return new List<Nationality>()
            {
                new Nationality() { NationalityID=1, Detail="Afghan", Active=1},
                new Nationality() { NationalityID=2, Detail="Albanian", Active=1},
                new Nationality() { NationalityID=3, Detail="Algerian", Active=1},
                new Nationality() { NationalityID=4, Detail="American", Active=1},
                new Nationality() { NationalityID=5, Detail="Andorran", Active=1},
                new Nationality() { NationalityID=6, Detail="Angolan", Active=1},
                new Nationality() { NationalityID=7, Detail="Antiguans", Active=1},
                new Nationality() { NationalityID=8, Detail="Argentinean", Active=1},
                new Nationality() { NationalityID=9, Detail="Armenian", Active=1},
                new Nationality() { NationalityID=10, Detail="Australian", Active=1},
                new Nationality() { NationalityID=11, Detail="Austrian", Active=1},
                new Nationality() { NationalityID=12, Detail="Azerbaijani", Active=1},
                new Nationality() { NationalityID=13, Detail="Bahamian", Active=1},
                new Nationality() { NationalityID=14, Detail="Bahraini", Active=1},
                new Nationality() { NationalityID=15, Detail="Bangladeshi", Active=1},
                new Nationality() { NationalityID=16, Detail="Barbadian", Active=1},
                new Nationality() { NationalityID=17, Detail="Barbudans", Active=1},
                new Nationality() { NationalityID=18, Detail="Batswana", Active=1},
                new Nationality() { NationalityID=19, Detail="Belarusian", Active=1},
                new Nationality() { NationalityID=20, Detail="Belgian", Active=1},
                new Nationality() { NationalityID=21, Detail="Belizean", Active=1},
                new Nationality() { NationalityID=22, Detail="Beninese", Active=1},
                new Nationality() { NationalityID=23, Detail="Bhutanese", Active=1},
                new Nationality() { NationalityID=24, Detail="Bolivian", Active=1},
                new Nationality() { NationalityID=25, Detail="Bosnian", Active=1},
                new Nationality() { NationalityID=26, Detail="Brazilian", Active=1},
                new Nationality() { NationalityID=27, Detail="British", Active=1},
                new Nationality() { NationalityID=28, Detail="Bruneian", Active=1},
                new Nationality() { NationalityID=29, Detail="Bulgarian", Active=1},
                new Nationality() { NationalityID=30, Detail="Burkinabe", Active=1},
                new Nationality() { NationalityID=31, Detail="Burmese", Active=1},
                new Nationality() { NationalityID=32, Detail="Burundian", Active=1},
                new Nationality() { NationalityID=33, Detail="Cambodian", Active=1},
                new Nationality() { NationalityID=34, Detail="Cameroonian", Active=1},
                new Nationality() { NationalityID=35, Detail="Canadian", Active=1},
                new Nationality() { NationalityID=36, Detail="Cape Verdean", Active=1},
                new Nationality() { NationalityID=37, Detail="Central African", Active=1},
                new Nationality() { NationalityID=38, Detail="Chadian", Active=1},
                new Nationality() { NationalityID=39, Detail="Chilean", Active=1},
                new Nationality() { NationalityID=40, Detail="Chinese", Active=1},
                new Nationality() { NationalityID=41, Detail="Colombian", Active=1},
                new Nationality() { NationalityID=42, Detail="Comoran", Active=1},
                new Nationality() { NationalityID=43, Detail="Congolese", Active=1},
                new Nationality() { NationalityID=44, Detail="Costa Rican", Active=1},
                new Nationality() { NationalityID=45, Detail="Croatian", Active=1},
                new Nationality() { NationalityID=46, Detail="Cuban", Active=1},
                new Nationality() { NationalityID=47, Detail="Cypriot", Active=1},
                new Nationality() { NationalityID=48, Detail="Czech", Active=1},
                new Nationality() { NationalityID=49, Detail="Danish", Active=1},
                new Nationality() { NationalityID=50, Detail="Djibouti", Active=1},
                new Nationality() { NationalityID=51, Detail="Dominican", Active=1},
                new Nationality() { NationalityID=52, Detail="Dutch", Active=1},
                new Nationality() { NationalityID=53, Detail="East Timorese", Active=1},
                new Nationality() { NationalityID=54, Detail="Ecuadorean", Active=1},
                new Nationality() { NationalityID=55, Detail="Egyptian", Active=1},
                new Nationality() { NationalityID=56, Detail="Emirian", Active=1},
                new Nationality() { NationalityID=57, Detail="Equatorial Guinean", Active=1},
                new Nationality() { NationalityID=58, Detail="Eritrean", Active=1},
                new Nationality() { NationalityID=59, Detail="Estonian", Active=1},
                new Nationality() { NationalityID=60, Detail="Ethiopian", Active=1},
                new Nationality() { NationalityID=61, Detail="Fijian", Active=1},
                new Nationality() { NationalityID=62, Detail="Filipino", Active=1},
                new Nationality() { NationalityID=63, Detail="Finnish", Active=1},
                new Nationality() { NationalityID=64, Detail="French", Active=1},
                new Nationality() { NationalityID=65, Detail="Gabonese", Active=1},
                new Nationality() { NationalityID=66, Detail="Gambian", Active=1},
                new Nationality() { NationalityID=67, Detail="Georgian", Active=1},
                new Nationality() { NationalityID=68, Detail="German", Active=1},
                new Nationality() { NationalityID=69, Detail="Ghanaian", Active=1},
                new Nationality() { NationalityID=70, Detail="Greek", Active=1},
                new Nationality() { NationalityID=71, Detail="Grenadian", Active=1},
                new Nationality() { NationalityID=72, Detail="Guatemalan", Active=1},
                new Nationality() { NationalityID=73, Detail="Guinea-Bissauan", Active=1},
                new Nationality() { NationalityID=74, Detail="Guinean", Active=1},
                new Nationality() { NationalityID=75, Detail="Guyanese", Active=1},
                new Nationality() { NationalityID=76, Detail="Haitian", Active=1},
                new Nationality() { NationalityID=77, Detail="Herzegovinian", Active=1},
                new Nationality() { NationalityID=78, Detail="Honduran", Active=1},
                new Nationality() { NationalityID=79, Detail="Hungarian", Active=1},
                new Nationality() { NationalityID=80, Detail="Icelander", Active=1},
                new Nationality() { NationalityID=81, Detail="Indian", Active=1},
                new Nationality() { NationalityID=82, Detail="Indonesian", Active=1},
                new Nationality() { NationalityID=83, Detail="Iranian", Active=1},
                new Nationality() { NationalityID=84, Detail="Iraqi", Active=1},
                new Nationality() { NationalityID=85, Detail="Irish", Active=1},
                new Nationality() { NationalityID=86, Detail="Israeli", Active=1},
                new Nationality() { NationalityID=87, Detail="Italian", Active=1},
                new Nationality() { NationalityID=88, Detail="Ivorian", Active=1},
                new Nationality() { NationalityID=89, Detail="Jamaican", Active=1},
                new Nationality() { NationalityID=90, Detail="Japanese", Active=1},
                new Nationality() { NationalityID=91, Detail="Jordanian", Active=1},
                new Nationality() { NationalityID=92, Detail="Kazakhstani", Active=1},
                new Nationality() { NationalityID=93, Detail="Kenyan", Active=1},
                new Nationality() { NationalityID=94, Detail="Kittian and Nevisian", Active=1},
                new Nationality() { NationalityID=95, Detail="Kuwaiti", Active=1},
                new Nationality() { NationalityID=96, Detail="Kyrgyz", Active=1},
                new Nationality() { NationalityID=97, Detail="Laotian", Active=1},
                new Nationality() { NationalityID=98, Detail="Latvian", Active=1},
                new Nationality() { NationalityID=99, Detail="Lebanese", Active=1},
                new Nationality() { NationalityID=100, Detail="Liberian", Active=1},
                new Nationality() { NationalityID=101, Detail="Libyan", Active=1},
                new Nationality() { NationalityID=102, Detail="Liechtensteiner", Active=1},
                new Nationality() { NationalityID=103, Detail="Lithuanian", Active=1},
                new Nationality() { NationalityID=104, Detail="Luxembourger", Active=1},
                new Nationality() { NationalityID=105, Detail="Macedonian", Active=1},
                new Nationality() { NationalityID=106, Detail="Malagasy", Active=1},
                new Nationality() { NationalityID=107, Detail="Malawian", Active=1},
                new Nationality() { NationalityID=108, Detail="Malaysian", Active=1},
                new Nationality() { NationalityID=109, Detail="Maldivan", Active=1},
                new Nationality() { NationalityID=110, Detail="Malian", Active=1},
                new Nationality() { NationalityID=111, Detail="Maltese", Active=1},
                new Nationality() { NationalityID=112, Detail="Marshallese", Active=1},
                new Nationality() { NationalityID=113, Detail="Mauritanian", Active=1},
                new Nationality() { NationalityID=114, Detail="Mauritian", Active=1},
                new Nationality() { NationalityID=115, Detail="Mexican", Active=1},
                new Nationality() { NationalityID=116, Detail="Micronesian", Active=1},
                new Nationality() { NationalityID=117, Detail="Moldovan", Active=1},
                new Nationality() { NationalityID=118, Detail="Monacan", Active=1},
                new Nationality() { NationalityID=119, Detail="Mongolian", Active=1},
                new Nationality() { NationalityID=120, Detail="Moroccan", Active=1},
                new Nationality() { NationalityID=121, Detail="Mosotho", Active=1},
                new Nationality() { NationalityID=122, Detail="Motswana", Active=1},
                new Nationality() { NationalityID=123, Detail="Mozambican", Active=1},
                new Nationality() { NationalityID=124, Detail="Namibian", Active=1},
                new Nationality() { NationalityID=125, Detail="Nauruan", Active=1},
                new Nationality() { NationalityID=126, Detail="Nepalese", Active=1},
                new Nationality() { NationalityID=127, Detail="Netherlander", Active=1},
                new Nationality() { NationalityID=128, Detail="New Zealander", Active=1},
                new Nationality() { NationalityID=129, Detail="Ni-Vanuatu", Active=1},
                new Nationality() { NationalityID=130, Detail="Nicaraguan", Active=1},
                new Nationality() { NationalityID=131, Detail="Nigerian", Active=1},
                new Nationality() { NationalityID=132, Detail="Nigerien", Active=1},
                new Nationality() { NationalityID=133, Detail="North Korean", Active=1},
                new Nationality() { NationalityID=134, Detail="Northern Irish", Active=1},
                new Nationality() { NationalityID=135, Detail="Norwegian", Active=1},
                new Nationality() { NationalityID=136, Detail="Omani", Active=1},
                new Nationality() { NationalityID=137, Detail="Pakistani", Active=1},
                new Nationality() { NationalityID=138, Detail="Palauan", Active=1},
                new Nationality() { NationalityID=139, Detail="Panamanian", Active=1},
                new Nationality() { NationalityID=140, Detail="Papua New Guinean", Active=1},
                new Nationality() { NationalityID=141, Detail="Paraguayan", Active=1},
                new Nationality() { NationalityID=142, Detail="Peruvian", Active=1},
                new Nationality() { NationalityID=143, Detail="Polish", Active=1},
                new Nationality() { NationalityID=144, Detail="Portuguese", Active=1},
                new Nationality() { NationalityID=145, Detail="Qatari", Active=1},
                new Nationality() { NationalityID=146, Detail="Romanian", Active=1},
                new Nationality() { NationalityID=147, Detail="Russian", Active=1},
                new Nationality() { NationalityID=148, Detail="Rwandan", Active=1},
                new Nationality() { NationalityID=149, Detail="Saint Lucian", Active=1},
                new Nationality() { NationalityID=150, Detail="Salvadoran", Active=1},
                new Nationality() { NationalityID=151, Detail="Samoan", Active=1},
                new Nationality() { NationalityID=152, Detail="San Marinese", Active=1},
                new Nationality() { NationalityID=153, Detail="Sao Tomean", Active=1},
                new Nationality() { NationalityID=154, Detail="Saudi", Active=1},
                new Nationality() { NationalityID=155, Detail="Scottish", Active=1},
                new Nationality() { NationalityID=156, Detail="Senegalese", Active=1},
                new Nationality() { NationalityID=157, Detail="Serbian", Active=1},
                new Nationality() { NationalityID=158, Detail="Seychellois", Active=1},
                new Nationality() { NationalityID=159, Detail="Sierra Leonean", Active=1},
                new Nationality() { NationalityID=160, Detail="Singaporean", Active=1},
                new Nationality() { NationalityID=161, Detail="Slovakian", Active=1},
                new Nationality() { NationalityID=162, Detail="Slovenian", Active=1},
                new Nationality() { NationalityID=163, Detail="Solomon Islander", Active=1},
                new Nationality() { NationalityID=164, Detail="Somali", Active=1},
                new Nationality() { NationalityID=165, Detail="South African", Active=1},
                new Nationality() { NationalityID=166, Detail="South Korean", Active=1},
                new Nationality() { NationalityID=167, Detail="Spanish", Active=1},
                new Nationality() { NationalityID=168, Detail="Sri Lankan", Active=1},
                new Nationality() { NationalityID=169, Detail="Sudanese", Active=1},
                new Nationality() { NationalityID=170, Detail="Surinamer", Active=1},
                new Nationality() { NationalityID=171, Detail="Swazi", Active=1},
                new Nationality() { NationalityID=172, Detail="Swedish", Active=1},
                new Nationality() { NationalityID=173, Detail="Swiss", Active=1},
                new Nationality() { NationalityID=174, Detail="Syrian", Active=1},
                new Nationality() { NationalityID=175, Detail="Taiwanese", Active=1},
                new Nationality() { NationalityID=176, Detail="Tajik", Active=1},
                new Nationality() { NationalityID=177, Detail="Tanzanian", Active=1},
                new Nationality() { NationalityID=178, Detail="Thai", Active=1},
                new Nationality() { NationalityID=179, Detail="Togolese", Active=1},
                new Nationality() { NationalityID=180, Detail="Tongan", Active=1},
                new Nationality() { NationalityID=181, Detail="Trinidadian or Tobagonian", Active=1},
                new Nationality() { NationalityID=182, Detail="Tunisian", Active=1},
                new Nationality() { NationalityID=183, Detail="Turkish", Active=1},
                new Nationality() { NationalityID=184, Detail="Tuvaluan", Active=1},
                new Nationality() { NationalityID=185, Detail="Ugandan", Active=1},
                new Nationality() { NationalityID=186, Detail="Ukrainian", Active=1},
                new Nationality() { NationalityID=187, Detail="Uruguayan", Active=1},
                new Nationality() { NationalityID=188, Detail="Uzbekistani", Active=1},
                new Nationality() { NationalityID=189, Detail="Venezuelan", Active=1},
                new Nationality() { NationalityID=190, Detail="Vietnamese", Active=1},
                new Nationality() { NationalityID=191, Detail="Welsh", Active=1},
                new Nationality() { NationalityID=192, Detail="Yemenite", Active=1},
                new Nationality() { NationalityID=193, Detail="Zambian", Active=1},
                new Nationality() { NationalityID=194, Detail="Zimbabwean", Active=1},
                new Nationality() { NationalityID=195, Detail="Not Applicable", Active=1},
                new Nationality() { NationalityID=196, Detail="Not Provided", Active=1},
                new Nationality() { NationalityID=197, Detail="Not Known", Active=1},
                new Nationality() { NationalityID=198, Detail="test", Active=0}
            };
        }

        public static Nationality GetNationalityByDetail(string c)
        {
            return GetNationalityList().Where(x => x.Detail == c).FirstOrDefault();
        }

        public static Nationality GetNationalityByID(int id)
        {
            return GetNationalityList().Where(x => x.NationalityID == id).FirstOrDefault();
        }
    }
}