INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'FAQs');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'FAQ added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'FAQ amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'FAQ deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Warrant Records');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Warrant added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Warrant amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Warrant deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Child Abduction Records');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'ChildAbduction added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'ChildAbduction amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'ChildAbduction deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Contacts');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Contact added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Contact amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Contact deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Contact Types');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'ContactType added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'ContactType amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'ContactType deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Documents');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Document added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Document amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Document deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Document Statuses');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'DocumentStatus added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'DocumentStatus amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'DocumentStatus deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Templates');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Template added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Template amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Template deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Document Types');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'DocumentType added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'DocumentType amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'DocumentType deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'AttendanceNotes');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'AttendanceNote added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'AttendanceNote amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'AttendanceNote deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Phone Codes');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'AttendanceNoteCode added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'AttendanceNoteCode amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'AttendanceNoteCode deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Tipstaff Record/Solicitors');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'TipstaffRecordSolicitor added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'TipstaffRecordSolicitor amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'TipstaffRecordSolicitor deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Solicitors');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Solicitor added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Solicitor amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Solicitor deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Solicitor Firms');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'SolicitorFirm added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'SolicitorFirm amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'SolicitorFirm deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Protective Markings');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'ProtectiveMarking added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'ProtectiveMarking amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'ProtectiveMarking deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Results');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Result added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Result amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Result deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Case Statuses');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'CaseStatus added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'CaseStatus amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'CaseStatus deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Case Reviews');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'CaseReview added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'CaseReview amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'CaseReview deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Case Review Statuses');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'CaseReviewStatus added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'CaseReviewStatus amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'CaseReviewStatus deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Genders');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Gender added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Gender amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Gender deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Countries');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Country added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Country amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Country deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Divisions');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Division added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Division amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Division deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Children');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Child added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Child amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Child deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Respondents');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Respondent added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Respondent amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Respondent deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Child Relationships');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'ChildRelationship added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'ChildRelationship amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'ChildRelationship deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Salutations');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Salutation added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Salutation amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Salutation deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Contemnors');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'CAOrderTypes');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Addressess');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Contemnor added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'CAOrderType added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Address added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Contemnor amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'CAOrderType amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Address amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Contemnor deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'CAOrderType deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Address deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Nationalities');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Nationality added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Nationality amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Nationality deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Applicants');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Applicant added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Applicant amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Applicant deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'DeletedTipstaffRecords');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'DeletedTipstaffRecord added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'DeletedReasons');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'DeletedReason added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'DeletedReason amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'DeletedReason deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'PoliceForces');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'PoliceForce added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'PoliceForce amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'PoliceForce deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'TipstaffPoliceForces');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'TipstaffPoliceForce added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'TipstaffPoliceForce amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'TipstaffPoliceForce deleted');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'Users amended');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'User added');
INSERT INTO dbo."AuditEventDescriptions" ("AuditDescription") VALUES (N'User amended');