CREATE TABLE [dbo].[Respondents] (
    [respondentID]        INT            IDENTITY (1, 1) NOT NULL,
    [nameLast]            NVARCHAR (50)  NOT NULL,
    [nameFirst]           NVARCHAR (50)  NULL,
    [nameMiddle]          NVARCHAR (50)  NULL,
    [dateOfBirth]         DATETIME       NULL,
    [genderID]            INT            NOT NULL,
    [childRelationshipID] INT            NOT NULL,
    [hairColour]          NVARCHAR (50)  NOT NULL,
    [eyeColour]           NVARCHAR (50)  NOT NULL,
    [height]              NVARCHAR (50)  NOT NULL,
    [build]               NVARCHAR (50)  NOT NULL,
    [specialfeatures]     NVARCHAR (250) NOT NULL,
    [countryID]           INT            NOT NULL,
    [riskOfViolence]      NVARCHAR (100) NOT NULL,
    [riskOfDrugs]         NVARCHAR (100) NOT NULL,
    [tipstaffRecordID]    INT            NOT NULL,
    [nationalityID]       INT            NULL,
    [skinColourID]        INT            NULL,
    [PNCID]               NVARCHAR (30)  DEFAULT ('') NULL,
    PRIMARY KEY CLUSTERED ([respondentID] ASC),
    CONSTRAINT [Respondent_childRelationship] FOREIGN KEY ([childRelationshipID]) REFERENCES [dbo].[ChildRelationships] ([childRelationshipID]) ON DELETE CASCADE,
    CONSTRAINT [Respondent_country] FOREIGN KEY ([countryID]) REFERENCES [dbo].[Countries] ([countryID]) ON DELETE CASCADE,
    CONSTRAINT [Respondent_gender] FOREIGN KEY ([genderID]) REFERENCES [dbo].[Genders] ([genderID]) ON DELETE CASCADE,
    CONSTRAINT [Respondent_nationality] FOREIGN KEY ([nationalityID]) REFERENCES [dbo].[Nationalities] ([nationalityID]) ON DELETE CASCADE,
    CONSTRAINT [Respondent_skinColour] FOREIGN KEY ([skinColourID]) REFERENCES [dbo].[SkinColours] ([skinColourID]) ON DELETE CASCADE,
    CONSTRAINT [Respondent_tipstaffRecord] FOREIGN KEY ([tipstaffRecordID]) REFERENCES [dbo].[TipstaffRecords] ([tipstaffRecordID]) ON DELETE CASCADE
);

