CREATE TABLE [dbo].[TipstaffRecords] (
    [tipstaffRecordID]    INT            IDENTITY (1, 1) NOT NULL,
    [createdBy]           NVARCHAR (50)  NOT NULL,
    [createdOn]           DATETIME       NOT NULL,
    [protectiveMarkingID] INT            NOT NULL,
    [resultID]            INT            NULL,
    [nextReviewDate]      DATETIME       NOT NULL,
    [resultDate]          DATETIME       NULL,
    [arrestCount]         INT            NULL,
    [prisonCount]         INT            NULL,
    [resultEnteredBy]     NVARCHAR (50)  NULL,
    [caseStatusID]        INT            NOT NULL,
    [sentSCD26]           DATETIME       NULL,
    [orderDated]          DATETIME       NULL,
    [orderReceived]       DATETIME       NULL,
    [officerDealing]      NVARCHAR (50)  NULL,
    [caOrderTypeID]       INT            NULL,
    [caseNumber]          NVARCHAR (50)  NULL,
    [expiryDate]          DATETIME       NULL,
    [divisionID]          INT            NULL,
    [Discriminator]       NVARCHAR (128) NOT NULL,
    [EldestChild]         NVARCHAR (50)  NULL,
    [RespondentName]      NVARCHAR (153) NULL,
    [DateExecuted]        DATETIME       NULL,
    [NPO]                 NVARCHAR (30)  DEFAULT ('') NULL,
    [DateCirculated]      DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([tipstaffRecordID] ASC),
    CONSTRAINT [ChildAbduction_caOrderType] FOREIGN KEY ([caOrderTypeID]) REFERENCES [dbo].[CAOrderTypes] ([caOrderTypeID]) ON DELETE CASCADE,
    CONSTRAINT [TipstaffRecord_caseStatus] FOREIGN KEY ([caseStatusID]) REFERENCES [dbo].[CaseStatus] ([caseStatusID]) ON DELETE CASCADE,
    CONSTRAINT [TipstaffRecord_protectiveMarking] FOREIGN KEY ([protectiveMarkingID]) REFERENCES [dbo].[ProtectiveMarkings] ([protectiveMarkingID]) ON DELETE CASCADE,
    CONSTRAINT [TipstaffRecord_result] FOREIGN KEY ([resultID]) REFERENCES [dbo].[Results] ([resultID]),
    CONSTRAINT [Warrant_division] FOREIGN KEY ([divisionID]) REFERENCES [dbo].[Divisions] ([divisionID]) ON DELETE CASCADE
);

