CREATE TABLE [dbo].[Children] (
    [childID]          INT            IDENTITY (1, 1) NOT NULL,
    [nameLast]         NVARCHAR (50)  NOT NULL,
    [nameFirst]        NVARCHAR (50)  NULL,
    [nameMiddle]       NVARCHAR (50)  NULL,
    [dateOfBirth]      DATETIME       NULL,
    [genderID]         INT            NOT NULL,
    [height]           NVARCHAR (50)  NOT NULL,
    [build]            NVARCHAR (50)  NOT NULL,
    [hairColour]       NVARCHAR (50)  NOT NULL,
    [eyeColour]        NVARCHAR (50)  NOT NULL,
    [specialfeatures]  NVARCHAR (250) NOT NULL,
    [countryID]        INT            NOT NULL,
    [tipstaffRecordID] INT            NOT NULL,
    [nationalityID]    INT            NULL,
    [skinColourID]     INT            NULL,
    [PNCID]            NVARCHAR (30)  DEFAULT ('') NULL,
    PRIMARY KEY CLUSTERED ([childID] ASC),
    CONSTRAINT [Child_childAbduction] FOREIGN KEY ([tipstaffRecordID]) REFERENCES [dbo].[TipstaffRecords] ([tipstaffRecordID]) ON DELETE CASCADE,
    CONSTRAINT [Child_country] FOREIGN KEY ([countryID]) REFERENCES [dbo].[Countries] ([countryID]) ON DELETE CASCADE,
    CONSTRAINT [Child_gender] FOREIGN KEY ([genderID]) REFERENCES [dbo].[Genders] ([genderID]) ON DELETE CASCADE,
    CONSTRAINT [Child_nationality] FOREIGN KEY ([nationalityID]) REFERENCES [dbo].[Nationalities] ([nationalityID]) ON DELETE CASCADE,
    CONSTRAINT [Child_skinColour] FOREIGN KEY ([skinColourID]) REFERENCES [dbo].[SkinColours] ([skinColourID]) ON DELETE CASCADE
);

